Repository Jesuitman/m3-rancid-tomatillos, pull requests merged in 2023-12, with the labels that each got.

#3 Component/card back
  cypress.config.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package.json
  pull_request_template.md
  src/App.js
  src/PosterBack.css
  src/PosterBack.js
  src/poster.css
  src/poster.js
Labels: component

#21 Adding in testing and a title for page
  cypress/e2e/posterviews.cy.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/PosterBack.css
  src/poster.css
Labels: bug, component

#22 Single movie view done
  src/FullMovie.css
  src/FullMovie.js
Labels: enhancement, component

#24 Feature/cypresswriting
  README.md
  cypress.config.js
  cypress/e2e/posterviews.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/mock-data.json
  ezgif-1-a2537a03b6.gif
  src/FullMovie.css
  src/FullMovie.js
  src/Home.css
  src/Home.js
  src/PosterBack.css
  src/PosterBack.js
Labels: enhancement, component

#26 Feature/filtermovies
  src/Home.js
Labels: bug, component
